version: 2.23.3

services:
  story:
    build:
      context: .
      dockerfile: ./src/backend/Zenthrill.WebAPI/Dockerfile
    ports:
      - 8081:80
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80

  story_consumer:
    build:
      context: .
      dockerfile: ./src/backend/Zenthrill.Story.Consumer/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=Docker

  graph_db:
    image: neo4j:enterprise
    ports:
      - ${GRAPH_DATABASE_EXTERNAL_PORT}:${GRAPH_DATABASE_INTERNAL_PORT}
      - ${GRAPH_DATABASE_BROWSER_EXTERNAL_PORT}:${GRAPH_DATABASE_BROWSER_INTERNAL_PORT}
    environment:
      - NEO4J_AUTH=${GRAPH_DATABASE_USER}/${GRAPH_DATABASE_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./volumes/graph_database:/data \
      - ./volumes/graph_database:/logs \
      - ./volumes/graph_database:/var/lib/neo4j/import \
      - ./volumes/graph_database:/plugins \

  db:
    image: postgres:latest
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGUSER=${DB_USER}
    volumes:
      - ./volumes/main_database:/var/lib/postgresql
      - ./Sql:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  story_migrator:
    build:
      context: ./src/migrations
      dockerfile: ./Zenthrill.DbMigrator/Dockerfile
    depends_on: 
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_CONNECTION_STRING=Host=db;Port=${DB_INTERNAL_PORT};User ID=${DB_USER};Password=${DB_PASSWORD};Database=${STORY_DB_NAME}

  auth_migrator:
    build:
      context: ./src
      dockerfile: ./migrations/Zenthrill.Auth.DbMigrator/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_CONNECTION_STRING=Host=db;Port=${DB_INTERNAL_PORT};User ID=${DB_USER};Password=${DB_PASSWORD};Database=${AUTH_DB_NAME}

  identity_server:
    build:
      context: .
      dockerfile: ./src/backend/Zenthrill.Auth.WebAPI/Dockerfile
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_CONNECTION_STRING=Host=db;Port=${DB_INTERNAL_PORT};User ID=${DB_USER};Password=${DB_PASSWORD};Database=${AUTH_DB_NAME}
      - ASPNETCORE_URLS=http://+:80

  story_broker:
    image: rabbitmq:3.10.7-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${STORY_BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${STORY_BROKER_PASSWORD}
    ports:
      - ${STORY_BROKER_BROWSER_EXTERNAL_PORT}:${STORY_BROKER_BROWSER_INTERNAL_PORT}
      - ${STORY_BROKER_EXTERNAL_PORT}:${STORY_BROKER_INTERNAL_PORT}

  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=${STORY_REDIS_PASSWORD}
    ports:
      - ${STORY_REDIS_EXTERNAL_PORT}:${STORY_REDIS_INTERNAL_PORT}

  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - CLEAR_TMP_FOLDER=0
    volumes:
      - ./volumes/.localstack:/tmp/localstack
      -  ./create-resources.sh:/etc/localstack/init/ready.d/create-resources.sh