version: 2.23.3

services:
  graph_database:
    image: neo4j:enterprise
    ports:
      - ${GRAPH_DATABASE_EXTERNAL_PORT}:${GRAPH_DATABASE_INTERNAL_PORT}
      - ${GRAPH_DATABASE_BROWSER_EXTERNAL_PORT}:${GRAPH_DATABASE_BROWSER_INTERNAL_PORT}
    environment:
      - NEO4J_AUTH=${GRAPH_DATABASE_USER}/${GRAPH_DATABASE_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./volumes/graph_database:/data \
      - ./volumes/graph_database:/logs \
      - ./volumes/graph_database:/var/lib/neo4j/import \
      - ./volumes/graph_database:/plugins \

  main_database:
    image: postgres:latest
    ports:
      - ${MAIN_DATABASE_EXTERNAL_PORT}:${MAIN_DATABASE_INTERNAL_PORT}
    environment:
      - POSTGRES_PASSWORD=${MAIN_DATABASE_PASSWORD}
      - POSTGRES_USER=${MAIN_DATABASE_USER}
      - POSTGRES_DB=${MAIN_DATABASE_NAME}
    volumes:
      - ./volumes/main_database:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  main_migrator:
    build:
      context: ./src/migrations
      dockerfile: ./Zenthrill.DbMigrator/Dockerfile
    depends_on: 
      main_database:
        condition: service_healthy
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_CONNECTION_STRING=Host=main_database;Port=${MAIN_DATABASE_INTERNAL_PORT};User ID=${MAIN_DATABASE_USER};Password=${MAIN_DATABASE_PASSWORD};Database=${MAIN_DATABASE_NAME}

  story_broker:
    image: rabbitmq:3.10.7-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${STORY_BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${STORY_BROKER_PASSWORD}
    ports:
      - ${STORY_BROKER_BROWSER_EXTERNAL_PORT}:${STORY_BROKER_BROWSER_INTERNAL_PORT}
      - ${STORY_BROKER_EXTERNAL_PORT}:${STORY_BROKER_INTERNAL_PORT}

  story_redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=${STORY_REDIS_PASSWORD}
    ports:
      - ${STORY_REDIS_EXTERNAL_PORT}:${STORY_REDIS_INTERNAL_PORT}

  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - CLEAR_TMP_FOLDER=0
    volumes:
      - ./volumes/.localstack:/tmp/localstack
      -  ./create-resources.sh:/etc/localstack/init/ready.d/create-resources.sh