version: 2.23.3

services: 
  main_database:
    image: postgres:latest
    ports:
      - ${MAIN_DATABASE_EXTERNAL_PORT}:${MAIN_DATABASE_INTERNAL_PORT}
    environment:
      - POSTGRES_PASSWORD=${MAIN_DATABASE_PASSWORD}
      - POSTGRES_USER=${MAIN_DATABASE_USER}
      - POSTGRES_DB=${MAIN_DATABASE_NAME}
    volumes:
      - ./volumes/main_database:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  main_migrator:
    build:
      context: ./src/migrations
      dockerfile: ./Zenthrill.DbMigrator/Dockerfile
    depends_on: 
      main_database:
        condition: service_healthy
    restart: on-failure
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_CONNECTION_STRING=Host=main_database;Port=${MAIN_DATABASE_INTERNAL_PORT};User ID=${MAIN_DATABASE_USER};Password=${MAIN_DATABASE_PASSWORD};Database=${MAIN_DATABASE_NAME}
