version: 2.23.3

services:
  graph_database:
    image: neo4j:enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./volumes/benchmarking/graph_database:/data \
      - ./volumes/benchmarking/graph_database:/logs \
      - ./volumes/benchmarking/graph_database:/var/lib/neo4j/import \
      - ./volumes/benchmarking/graph_database:/plugins \

  main_database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./volumes/benchmarking/main_database:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5